
---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: class65
value: 999999934
globalDefault: false
preemptionPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  name: job-1-bert-train-bert-base-cased-cuda-epoch2
spec:
  priorityClassName: class65  # Set your PriorityClass name here
  containers:
  - name: c-job-1-bert-train-bert-base-cased-cuda-epoch2
    image:  nba556677/train_tasks:template
    #imagePullPolicy: Always
    command: ["python", "/app/template/bert_train.py", "--n_epoch", "2"]
    env:
    - name: GPU_MEMORY
      value: "7967"
    - name: GPU_COMPTIME
      value: "65"
    - name: CPU_COMPTIME
      value: "780"
    resources:
      limits:
        # MiB
         aliyun.com/gpu-mem: 7967
  restartPolicy: Never


---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: class130
value: 999999869
globalDefault: false
preemptionPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  name: job-2-bert-train-bert-base-cased-cuda-epoch4
spec:
  priorityClassName: class130  # Set your PriorityClass name here
  containers:
  - name: c-job-2-bert-train-bert-base-cased-cuda-epoch4
    image:  nba556677/train_tasks:template
    #imagePullPolicy: Always
    command: ["python", "/app/template/bert_train.py", "--n_epoch", "4"]
    env:
    - name: GPU_MEMORY
      value: "7967"
    - name: GPU_COMPTIME
      value: "130"
    - name: CPU_COMPTIME
      value: "1560"
    resources:
      limits:
        # MiB
         aliyun.com/gpu-mem: 7967
  restartPolicy: Never


---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: class196
value: 999999803
globalDefault: false
preemptionPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  name: job-3-bert-train-bert-base-cased-cuda-epoch6
spec:
  priorityClassName: class196  # Set your PriorityClass name here
  containers:
  - name: c-job-3-bert-train-bert-base-cased-cuda-epoch6
    image:  nba556677/train_tasks:template
    #imagePullPolicy: Always
    command: ["python", "/app/template/bert_train.py", "--n_epoch", "6"]
    env:
    - name: GPU_MEMORY
      value: "7967"
    - name: GPU_COMPTIME
      value: "196"
    - name: CPU_COMPTIME
      value: "2352"
    resources:
      limits:
        # MiB
         aliyun.com/gpu-mem: 7967
  restartPolicy: Never

