apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
  namespace: ls
  labels:
    app: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: nba556677/chatbot:vllm
        #imagePullPolicy: Always
        command: ["python", "-m", "vllm.entrypoints.openai.api_server", "--model", "facebook/opt-6.7b", "--gpu-memory-utilization", "0.75"]
        ports:
        - containerPort: 8000
