apiVersion: v1
kind: Pod
metadata:
  name: be-job-6-imgclassification-train-cuda-epoch10
  namespace: be
spec:
  containers:
  - command:
    - python
    - /app/template/imgclassification-train.py
    - --n_epoch
    - '10'
    env:
    - name: GPU_MEMORY
      value: '1747'
    - name: GPU_COMPTIME
      value: '63'
    - name: CPU_COMPTIME
      value: '756'
    image: nba556677/train_tasks:template
    name: c-be-job-6-imgclassification-train-cuda-epoch10
    resources:
      limits:
        aliyun.com/gpu-mem: 1747
  nodeSelector:
    kubernetes.io/hostname: node6
  restartPolicy: Never
