
---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: class30
value: 999999930
globalDefault: false
preemptionPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  name: run-1-job-1-llm-data-wrangle
  namespace: ls
spec:
  priorityClassName: class30  # Set your PriorityClass name here
  containers:
  - name: c-run-1-job-1-llm-data-wrangle
    image:  nba556677/inference:flexgen
    imagePullPolicy: Always
    command: ["bash", "./test_single_query_case.sh"]
    env:
    - name: GPU_MEMORY
      value: "1747"
    - name: GPU_COMPTIME
      value: "63"
    - name: CPU_COMPTIME
      value: "756"
    resources:
      limits:
        # MiB
         aliyun.com/gpu-mem: 16000
  restartPolicy: Never

